@startuml frame_full_real

package node <<Node>> $node {
    package SR_config <<Rectangle>> $SR_config {
        struct "Описание\nкоммутируемой\nпеременной" as link_var_discriptor {
            + индекс_в_буфере : size_t
            + значение_связи : float*
        }
        
        class "Коммуникатор" as Link_MPI $Link_MPI {
            - номер_узла : int
            - список_на_передачу : 
            std::vector<Описание коммутируемой переменной>*
            - список_на_приём :
            std::vector<Описание коммутируемой переменной>*
            + размер_буфера_на_передачу : int
            + размер_буфера_на_приём : int
            + буфер_на_передачу : float*
            + буфер_на_приём : float*
            __
            + Конструктор(номер_узла : int)
            + Деструктор()
            + получение_номера_узла() : int
            + добавление_в_список_на_передачу(переменная : float*,
            индекс_в_буфере : size_t) : void
            + добавление_в_список_на_приём(переменная : float*,
            индекс_в_буфере : size_t) : void
            + установка_локального_порядка_выдачи() : void
            + заполнение_буфера_на_передачу() : void
            + заполнение_буфера_на_приём() : void
            + выделение_буфера_на_передачу() : void
            + выделение_буфера_на_приём() : void
        }
        note right of Link_MPI::установка_локального_порядка_выдачи
            Сортировка в порядке
            возрастания индексов
        end note
        
        struct "Описание \nпеременной" as SR_var_descriptor $SR_var_descriptor {
            + имя_переменной : const char*
            + имя_алгоритма : const char*
            + счётчик_использований : size_t
            + значение_связи : float*
        }
        
        class "Посредник" as SR_var_list {
            - список_входов : 
            std::vector<Описание переменной>*
            - список_выходов : 
            std::vector<Описание переменной>*
            - массив_значений_связей : float*

            - список_требуемых_переменных : 
            std::vector<Описание переменной>*
            - массив_значений_требуемых_связей : float*
            __
            + Конструктор()
            + Деструктор()
            .. Прочие служебные функции ..
            + регистрация_входов(имя_алгоритма : const char*, 
            имя_входа : const char*, вход : float**) : void
            + регистрация_выходов(имя_алгоритма : const char*, 
            имя_выхода : const char*, выход : float**) : void
            + создание_связей() : void
        }
        note bottom of SR_var_list : Посредник заведует\nпортами и связями\nвсех алгоритмов
        note right of SR_var_list::создание_связей
            Выделение памяти 
            под выходные переменные
            и связывание со входными
        end note
        
        class "Настройки" as SR_Settings $SR_Settings {
            + список_локальных_переменных : Посредник*
            __
            + Конструктор()
            + Деструктор()
            + поиск_алгоритмов(список_алгоритмов : Алгоритм***) : size_t
        }
    }

    package alg_base <<Rectangle>> $alg_base {
        abstract "Алгоритм" as SR_calc_proc $SR_calc_proc {
            # список_имён_уставок : std::vector<const char*>*
            # список_уставок : std::vector<float**>*
            # список_имён_входов : std::vector<const char*>*
            # список_входов : std::vector<float**>*
            # список_имён_выходов : std::vector<const char*>*
            # список_выходов : std::vector<float**>*
            + период_расчёта : int
            + имя_алгоритма : const char*
            + флаг_готовности : bool
            __
            # добавление_уставки(уставка : float**, имя : const char*, 
            начальное_значение : float) : void
            # добавление_входа(вход : float**, 
            имя : const char*) : void
            # добавление_выхода(выход : float**, 
            имя : const char*) : void
            + Конструктор()
            + Деструктор()
            + регистрация_переменных(посредник : Посредник*) : int         
            + {abstract} расчёт() : void
            .. Прочие функции для взаимодействия с алгоритмами ..
        }
        note right of SR_calc_proc : Базовый \nфункционал \nалгоритмов
        note left of SR_calc_proc::Конструктор()
            Выделение памяти под списки
        end note
        note left of SR_calc_proc::период_расчёта
            Параметр определяет 
            категорию "быстрый/медленный".
            Задаётся номинальный такт расчёта в мс.
        end note
        note left of SR_calc_proc::флаг_готовности
            Алгоритм не работает, 
            если его входы не подключены
        end note
    }

    package SR_ctl <<Rectangle>> $SR_ctl {
        class "Создатель" as SR_ctl_type $SR_ctl_type {
            - связи_MPI : Коммуникатор**
            - настройки : Настройки*
            - список_алгоритмов : Алгоритм**
            - фактическое_время_такта : double
            - число_найденных_алгоритмов : size_t
            __
            + Конструктор()
            + Деструктор()
            + инициализация() : void
            + работа() : void
        }
        note left of SR_ctl_type::инициализация()
            Поиск алгоритмов,
            регистрация их переменных 
            и создание связей
        end note
        note left of SR_ctl_type::работа()
            Запуск алгоритмов на выполнение
            в порядке агрегации
        end note
    }

    class "Алгоритм" as SR_auto_ctl $SR_auto_ctl {
        .. Входные переменные ..
        - вход_0 : float*
        - имя_входа_0 : const char*
        ...
        - вход_i : float*
        - имя_входа_i : const char*
        .. Выходные переменные ..
        - выход_0 : float*
        - имя_выхода_0 : const char*
        ...
        - выход_o : float*
        - имя_выхода_o : const char*
        .. Уставки ..
        - уставка_0 : float*
        - имя_уставки_0 : const char*
        - начальное_значение_0 : float
        ...
        - уставка_s : float*
        - имя_уставки_s : const char*
        - начальное_значение_s : float
        .. Пользовательские поля ..
        __
        + Конструктор()
        + Деструктор()
        + {abstract} расчёт() : void
        .. Пользовательские функции ..
    }
    note right of SR_auto_ctl : Расширенный \nфункционал \nалгоритмов
    note left of SR_auto_ctl::Конструктор()
        Добавление входов, выходов и уставок
    end note
    note left of SR_auto_ctl::расчёт()
        Реализация расчётной процедуры
    end note
}

SR_ctl_type::связи_MPI o--> "0..*" Link_MPI
SR_ctl_type::настройки *--> "1" SR_Settings
SR_ctl_type::список_алгоритмов o--> "0..*" SR_calc_proc : Агрегация \nалгоритмов

Link_MPI ..> link_var_discriptor

SR_var_list ..> SR_var_descriptor

SR_Settings *--> "1" SR_var_list
SR_Settings::поиск_алгоритмов .....> SR_calc_proc : Поиск \nалгоритмов

SR_var_list <.. SR_calc_proc::регистрация_переменных : Регистрация \nпеременных

SR_calc_proc "0..*" <|-- SR_auto_ctl : Подключение пользовательских алгоритмов

@enduml
