@startuml simple_plus
skinparam groupInheritance 4

package node <<Node>> $node {
    package SR_config <<Rectangle>> $SR_config {
        struct "Описание\nкоммутируемой\nпеременной" as link_var_discriptor {

        }
        
        class "Коммуникатор" as Link_MPI $Link_MPI {

        }
        
        struct "Описание \nпеременной" as SR_var_descriptor $SR_var_descriptor {

        }
        
        class "Посредник" as SR_var_list {

        }
        
        class "Настройки" as SR_Settings $SR_Settings {

        }
    }

    package alg_base <<Rectangle>> $alg_base {
        abstract "Алгоритм" as SR_calc_proc $SR_calc_proc {

        }
    }

    package SR_ctl <<Rectangle>> $SR_ctl {
        class "Создатель" as SR_ctl_type $SR_ctl_type {

        }
    }

    class "Алгоритм" as SR_auto_ctl $SR_auto_ctl {

    }
}

SR_ctl_type o--> "0..*" Link_MPI
SR_ctl_type *--> "1" SR_Settings
SR_ctl_type o-r-> "0..*" SR_calc_proc : Агрегация\nалгоритмов

Link_MPI ..> link_var_discriptor

SR_var_list ..> SR_var_descriptor

SR_Settings *--> "1" SR_var_list
SR_Settings .....> SR_calc_proc : Поиск\nалгоритмов

SR_var_list <.. SR_calc_proc : Регистрация\nпеременных

SR_calc_proc "0..*" <|-- SR_auto_ctl : Подключение\nпользовательских\nалгоритмов

@enduml
